# ----------------------------------------------------------------------------
#
# Package             : camel-extra
# Source Repo         : https://github.com/camel-extra/camel-extra
# Travis Job Link     : https://travis-ci.com/github/asellappen/camel-extra/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: java
arch:
 #  - amd64
    - ppc64le

dist: focal
before_install:
   - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-ppc64el/
# addons:
#   sonarcloud:
#     organization: "camel-extra" 
script: 
  - mvn clean install -B -e -X -PwithRatCheck,integration
#   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
jdk:
  - openjdk14
  - openjdk15
  - openjdk11
